name: 'Renan Action'
description: 'Create new releases after pushing to hmg branches'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  # secretName:
  #   description: 'The secret name'
  #   required: true
  # secretValue:
  #   description: 'The secret value'
  #   required: true
runs:
  using: 'node16'
  main: 'index.js'